[package]
name = "nuclear"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytestream = "0.4"
thiserror = "1.0"
png = "0.17"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"